# Project metadata (PEP 621) ===============================================
[project]
name = "FAST-PEDAGO"
description = "Lightweight interface to perform simplified OAD analysis using FAST-OAD"
readme = "README.md"
license = "GPL-3.0-only"
keywords = [
    "aircraft",
    "design",
    "multi-disciplinary",
    "teaching",
    "educational"
]
authors = [
    {name = "Ousmane SY", email = "Ousmane.SY@isae-supaero.fr>"},
    {name = "Eric MONTSERRAT ROBLES"},
    {name = "Marien GIORDANI"}
]
maintainers = [
    {name = "Florent LUTZ", email = "Florent.LUTZ2@isae-supaero.fr>"},
]
requires-python = ">=3.10,<3.15"

# User dependencies ------------------------------------------------------------
dependencies = [
    "fast-oad-core>=1.10.0",
    "fast-oad-cs25>=0.9.1",
    "ipywidgets>=7.7.2",
    "ipyvuetify>=1.9.4",
    "appmode>=0.9.0",
    "voila>=0.3.7",
    "click>=8.0.3",
    "lxml_html_clean",
]

[project.urls]
homepage = "https://github.com/supaero-aircraft-design/FAST-PEDAGO"


# Poetry settings ==============================================================
[tool.poetry]
requires-poetry = ">=2.0" # You should upgrade poetry to v2 using 'pipx upgrade poetry'
version = "1.0.4"
exclude = ["**/tests/**"]

#  Suitable classifiers based on python requirement and license are not automatically added if classifiers are statically defined in the project section
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Education",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Natural Language :: English",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Physics"
]

[tool.poetry.group.dev.dependencies]
wheel = "*"
tabula = "*"

[tool.poetry.group.test.dependencies]
pytest = "^5.2"
pytest-cov = "*"
nbval = "*"

[tool.poetry.group.doc.dependencies]
sphinx = "*"
sphinx-rtd-theme = "*"
sphinxcontrib-bibtex = "*"

[tool.poetry.group.lint.dependencies]
ruff = ">0.15.0, <0.16.0"

# Packaging system =============================================================
[build-system]
requires = [
    "poetry-core>=2.0.0,<3.0.0",
    "poetry-dynamic-versioning>=1.0.0,<2.0.0"
 ]
build-backend = "poetry_dynamic_versioning.backend"

# Pytest settings ==============================================================
[tool.pytest.ini_options]
minversion = "8.0"
addopts = "--cov-report term-missing --cov-report html --verbose"
testpaths = ["src"]
norecursedirs = ["dist", "build", ".tox", ".ipynb_checkpoints"]

[project.scripts]
    fast-pedago = "fast_pedago.app:main"