# This file is part of FAST-OAD_CS23-HE : A framework for rapid Overall Aircraft Design of Hybrid
# Electric Aircraft.
# Copyright (C) 2022 ISAE-SUPAERO

import ipywidgets as widgets

from IPython.display import display

# Create a withe box behind the info button
display(widgets.HTML("""<style>.white-vbox {background-color: white;}</style>"""))


def get_clear_all_button():

    # Creating and instantiating an info button
    clear_all_button = widgets.Button(description="")
    clear_all_button.icon = "fa-trash"
    clear_all_button.layout.width = "auto"
    clear_all_button.button_style = "danger"
    clear_all_button.tooltip = (
        "Press this button to clear ALL results generated by running this app."
    )

    return clear_all_button
