# This file is part of FAST-OAD_CS23-HE : A framework for rapid Overall Aircraft Design of Hybrid
# Electric Aircraft.
# Copyright (C) 2022 ISAE-SUPAERO

import os
import os.path as pth

import ipywidgets as widgets

from IPython.display import display

# Create a withe box behind the info button
display(widgets.HTML("""<style>.white-vbox {background-color: white;}</style>"""))


class ClearAllButton(widgets.Button):

    def __init__(self, display_main_tab, **kwargs):
        super().__init__(**kwargs)

        self.display_main_tab = display_main_tab

        # Creating and instantiating an info button
        self.icon = "fa-trash"
        self.layout.width = "auto"
        self.button_style = "danger"
        self.tooltip = (
            "Press this button to clear ALL results generated by running this app."
        )

        self.on_click(self.clear_all_files)

    def clear_all_files(self, event):

        # First, we switch back to the main tab of the sensitivity analysis screen which will
        # force a new check of available output file
        self.display_main_tab()
        # self.sensitivity_analysis_tab.selected_index = 0

        working_directory_path = pth.join(os.getcwd(), "workdir")
        input_directory_path = pth.join(working_directory_path, "inputs")
        output_directory_path = pth.join(working_directory_path, "outputs")

        # Remove all input files in the inputs directory
        input_file_list = os.listdir(input_directory_path)
        for file_name in input_file_list:
            file_path = pth.join(input_directory_path, file_name)

            # We keep the reference input_file and avoid deleting subdirectory
            if file_name != "reference_aircraft_input_file.xml" and not pth.isdir(
                file_path
            ):
                os.remove(file_path)

        # Remove all input files in the outputs directory, we can remove all .sql because they
        # are re-generated anyway
        output_file_list = os.listdir(output_directory_path)
        for file_name in output_file_list:
            file_path = pth.join(output_directory_path, file_name)

            # We keep the reference input_file and avoid deleting subdirectory
            if (
                file_name != "reference_aircraft_output_file.xml"
                and file_name != "reference_aircraft_flight_points.csv"
                and not pth.isdir(file_path)
            ):
                os.remove(file_path)