# This file is part of FAST-OAD_CS23-HE : A framework for rapid Overall Aircraft Design of Hybrid
# Electric Aircraft.
# Copyright (C) 2022 ISAE-SUPAERO

import os
import os.path as pth

import ipyvuetify as v

class ClearAllButton(v.Tooltip):
    """
    A button with a trash icon to clear all the input/output files
    in the work directory that are not the reference aircraft files

    The button displays a tooltip to inform the user of the behaviour
    of the button
    """

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.button = v.Btn(
            v_on = 'tooltip.on', 
            color = 'error', 
            children = [
                v.Icon(children=["fa-trash"])
            ],
            icon = True,
        )

        self.button.on_event("click", self.clear_all_files)

        
        self.top = True

        # The button has to be encapsulated by the tooltip 
        self.v_slots = [{
            'name': 'activator',
            'variable': 'tooltip',
            'children': self.button
        }]
        self.children = ['Press this button to clear ALL results generated by running this app.']


    def clear_all_files(self, widget, event, data):
        """
        Clear all files contained in "workdir", in subdirectories "inputs"
        and "outputs", that are not the files of the reference aircraft

        The subdirectories of workdir aere not deleted in the process
        """

        working_directory_path = pth.join(os.getcwd(), "workdir")
        input_directory_path = pth.join(working_directory_path, "inputs")
        output_directory_path = pth.join(working_directory_path, "outputs")

        # Remove all input files in the inputs directory
        input_file_list = os.listdir(input_directory_path)
        for file_name in input_file_list:
            file_path = pth.join(input_directory_path, file_name)

            # We keep the reference input_file and avoid deleting subdirectory
            if file_name != "reference_aircraft_input_file.xml" and not pth.isdir(
                file_path
            ):
                os.remove(file_path)

        # Remove all input files in the outputs directory, we can remove all .sql because they
        # are re-generated anyway
        output_file_list = os.listdir(output_directory_path)
        for file_name in output_file_list:
            file_path = pth.join(output_directory_path, file_name)

            # We keep the reference input_file and avoid deleting subdirectory
            if (
                file_name != "reference_aircraft_output_file.xml"
                and file_name != "reference_aircraft_flight_points.csv"
                and not pth.isdir(file_path)
            ):
                os.remove(file_path)